apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: stephengrider/multi-api
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis-server
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              value: postgres_password
            - name: PGPORT
              value: '5432'
          ports:
            - name: http
              containerPort: 5000
