apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-tls
  namespace: default
spec:
  secretName: k8s-multi-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.k8s-multi.com
  dnsNames:
    - www.k8s-multi.com
  acme:
    config:
      - http01:
          ingress: ingress-service
        domains:
          - www.k8s-multi.com
