sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

after_success:
  - docker build -t stephengrider/multi-client -f ./client/Dockerfile ./client
  - docker build -t stephengrider/multi-server -f ./server/Dockerfile ./server
  - docker build -t stephengrider/multi-worker -f ./worker/Dockerfile ./worker
  - docker build -t stephengrider/multi-nginx -f ./nginx/Dockerfile ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-west-2"
  app: "multi"
  env: "Multi-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "multi-env"
  on:
    branch: master