sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)
before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - openssl aes-256-cbc -K $encrypted_248412cf5212_key -iv $encrypted_248412cf5212_iv -in service-account.json.enc -out service-account.json -d
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud version
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k4multi-212920
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials k4cluster
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
